### ISSUE TITLE
Help to control multiple motors using TMC5160BOB and Arduino Mega

### ISSUE THREAD

**Issue by Mrugank12** [tommag/TMC5160_Arduino#9]
I am working on a 4 wheeled mobile robot with each wheel powered by a NEMA17 stepper and each stepper is connected to its individual TMC5160BOB . I want to control all 4 motors for forward backward motion as well as left right differential drive so i was wondering which will be the simplest method SPI or UART to control all 4 methods in simplest way. Any help would mean a lot as i am not very familiar with these boards.

**Comment by tommag** [comment]
Hello,
It really depends more on the ease of wiring. While testing, I have found that SPI is more reliable than UART, I reserve UART for projects where there is a long distance between the controller and the TMC5160 board because it needs less wires and is more resistent to electromagnetic perturbations but it's much more fiddly.
For a robot project where the boards will probably be close to each other and with only 4 motors, I would stick to the standard SPI.
